name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  continuous_integration_build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.2, head]
        operating-system: [ubuntu-latest]

    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Build
        run: bundle exec rake build

      - name: Test Gem
        run: bundle exec rake unit_tests
